[package]
name = "psql-col-test"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = {version="0.8.5", features=["postgres","runtime-tokio","macros"]}
tokio = {version="1.44.2", features=["full"]}
